const {app,BrowserWindow,ipcMain,safeStorage}=require('electron');const path=require('path');const crypto=require('crypto');const Store=require('electron-store').default;
const MIN_USD=10000;const ASSETS={BTC:{price:118000,network:'Bitcoin Mainnet',confirmations:3},ETH:{price:3700,network:'Ethereum Mainnet · Chain 1',confirmations:12},SOL:{price:185,network:'Solana Mainnet',confirmations:32},BNB:{price:790,network:'BNB Smart Chain · Chain 56',confirmations:15},POL:{price:.55,network:'Polygon PoS · Chain 137',confirmations:128}};
const DEPOSITS={BTC:'bc1qr58snsz9gey4mvcmf2e0gaxfya6hf49g07kcru',ETH:'0xA71D9E60235a29381366aeC4B6f57438b48E2768',SOL:'BXnNT1gyrSmHyfuR5k9CV1NcuP9emNVjnZBhgv95EpJg',BNB:'0xA71D9E60235a29381366aeC4B6f57438b48E2768',POL:'0xA71D9E60235a29381366aeC4B6f57438b48E2768'};
let session=false;let store;const attempts=new Map();const hash=(p,s)=>crypto.scryptSync(p,s,64).toString('hex');const clean=(x,n=128)=>typeof x==='string'?x.trim().slice(0,n):'';
function requireAuth(){if(!session)throw new Error('Authentication required')};function encryptionReady(){return safeStorage.isEncryptionAvailable()&&(process.platform!=='linux'||safeStorage.getSelectedStorageBackend()!=='basic_text')}function secureSet(k,v){if(!encryptionReady())throw new Error('A secure operating-system credential store is required');store.set(k,safeStorage.encryptString(JSON.stringify(v)).toString('base64'))};function secureGet(k){const x=store.get(k);if(!x)return null;if(!encryptionReady())throw new Error('Secure operating-system storage is unavailable');return JSON.parse(safeStorage.decryptString(Buffer.from(x,'base64')))}
function window(){const w=new BrowserWindow({width:1280,height:820,minWidth:960,minHeight:650,backgroundColor:'#07100d',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,webSecurity:true}});w.webContents.setWindowOpenHandler(()=>({action:'deny'}));w.webContents.on('will-navigate',(e,url)=>{if(!url.startsWith('file:')&&!url.startsWith('http://127.0.0.1:5173'))e.preventDefault()});if(!app.isPackaged)w.loadURL('http://127.0.0.1:5173');else w.loadFile(path.join(__dirname,'../dist/index.html'))}
app.whenReady().then(()=>{store=new Store({name:'secure-config'});window();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)window()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
ipcMain.handle('app:status',()=>({configured:!!store.get('admin'),authenticated:session,mainnetEnabled:false,minUsd:MIN_USD}));
ipcMain.handle('auth:setup',(_e,x)=>{if(store.get('admin'))throw new Error('Administrator already configured');const email=clean(x?.email,254).toLowerCase(),password=clean(x?.password,200);if(!/^\S+@\S+\.\S+$/.test(email)||password.length<14)throw new Error('Use a valid email and a password of at least 14 characters');const salt=crypto.randomBytes(32).toString('hex');secureSet('admin',{email,salt,digest:hash(password,salt)});session=true;return {ok:true,email}});
ipcMain.handle('auth:login',(_e,x)=>{const email=clean(x?.email,254).toLowerCase();const now=Date.now(),state=attempts.get(email)||{count:0,until:0};if(state.until>now)throw new Error('Too many attempts. Try again later.');const admin=secureGet('admin'),password=clean(x?.password,200);const valid=admin&&crypto.timingSafeEqual(Buffer.from(hash(password,admin.salt),'hex'),Buffer.from(admin.digest,'hex'))&&email===admin.email;if(!valid){state.count++;if(state.count>=5){state.until=now+300000;state.count=0}attempts.set(email,state);throw new Error('Invalid credentials')}attempts.delete(email);session=true;return {ok:true,email}});
ipcMain.handle('auth:logout',()=>{session=false;return {ok:true}});
ipcMain.handle('order:quote',(_e,x)=>{requireAuth();const symbol=clean(x?.sendAsset,4);const usd=Number(x?.usd);if(!ASSETS[symbol]||!Number.isFinite(usd)||usd<MIN_USD||usd>10000000)throw new Error('Order must be between $10,000 and $10,000,000');return {sendAmount:(usd/ASSETS[symbol].price).toFixed(8),receiveAmount:(usd*.9925).toFixed(2),network:ASSETS[symbol].network,confirmations:ASSETS[symbol].confirmations,expiresAt:new Date(Date.now()+900000).toISOString()}});
ipcMain.handle('order:create',(_e,x)=>{requireAuth();const symbol=clean(x?.sendAsset,4),receive=clean(x?.receiveAsset,8),wallet=clean(x?.destinationAddress,128),usd=Number(x?.usd);if(!ASSETS[symbol]||!['USDC','USDT','DAI','BTC','ETH'].includes(receive)||wallet.length<8||!Number.isFinite(usd)||usd<MIN_USD||usd>10000000)throw new Error('Invalid order request');const orders=secureGet('orders')||[];const order={id:crypto.randomUUID(),sendAsset:symbol,receiveAsset:receive,usd,status:'PENDING_COMPLIANCE',createdAt:new Date().toISOString(),destinationAddress:wallet,depositAddress:DEPOSITS[symbol],depositLocked:true};orders.unshift(order);secureSet('orders',orders.slice(0,1000));return {...order,depositAddress:undefined}});
ipcMain.handle('order:list',()=>{requireAuth();return (secureGet('orders')||[]).map(({depositAddress,...x})=>x)});
